heat_template_version: 2013-05-23

description: |
  Create 3 node Cassandra cluster using Chef.

parameters:

  external_network_id:
    type: string
    label: External Network
    description: UUID of a Neutron external network
    default: 15afc2c4-cfbf-4ead-ad0e-498909f3f71b

  ubuntu_image:
    type: string
    label: Base OS Image
    description: Name of image to use for servers
    default: ubuntu-14.04-server-amd64

  dns_server:
    type: string
    label: DNS Server
    description: Comma separated list of DNS servers
    default: "10.20.20.1"
    constraints:
      - allowed_pattern: "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}"
        description: Enter a valid IP address

  host_size:
     type: string
     label: Host Flavor
     description: Enter one available flavor type here
     default: m1.small
     constraints:
       - allowed_values:
         - m1.small
         - m1.medium
         - m1.large 

resources:
  # Create single network for all Cassandra nodes.
  cassandra_net:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: cassandra-network
  cassandra_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: cassandra-subnet
      cidr: 172.16.10.0/24
      # dns_nameservers: { get_param: dns_servers }
      dns_nameservers: [ { get_param: dns_server } ]
      enable_dhcp: true
      gateway_ip: 172.16.10.1
      network_id: { get_resource: cassandra_net }

  # Chef bootstrap needs internet access, so create gateway.
  cassandra_router:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      name: cassandra-router
  cassandra_router_gw:
    type: OS::Neutron::RouterGateway
    properties:
      network_id: { get_param: external_network_id }
      router_id: { get_resource: cassandra_router }
  router_int0:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: cassandra_router }
      subnet_id: { get_resource: cassandra_subnet }

  # Enable SSH to the hosts.
  host_secgrp:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Allow SSH access to hosts.
      name: host-secgrp
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22

  # Need to get seed server IP early, so explicitly create port.
  seed_port:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_resource: cassandra_net }
      security_groups:
        - { get_resource: host_secgrp }
  seed_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: external_network_id }
      port_id: { get_resource: seed_port }

  # Create ports for other nodes, in case they need to be slaves.
  host1_port:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_resource: cassandra_net }
      security_groups:
        - { get_resource: host_secgrp }
  host2_port:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_resource: cassandra_net }
      security_groups:
        - { get_resource: host_secgrp }

  # Provision instances.
  cassandra_seed_host:
    type: OS::Nova::Server
    properties:
      name: cassandra-seed
      image: { get_param: ubuntu_image }
      flavor: { get_param: host_size } 
      networks:
        - port: { get_resource: seed_port } 
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __seed_ipaddr__: { get_attr: [seed_port, fixed_ips, 0, ip_address] }
            __host1_ipaddr__: { get_attr: [host1_port, fixed_ips, 0, ip_address] }
            __host2_ipaddr__: { get_attr: [host2_port, fixed_ips, 0, ip_address] }
          template: |
            #cloud-config
            chef:
              install_type: "omnibus"
              omnibus_url: "https://www.chef.io/chef/install.sh"
              force_install: false
              server_url: "https://api.opscode.com/organizations/username"
              log_location: "/var/log/chef-client.log"
              validation_name: "username-validator"
              validation_key: |
                -----BEGIN RSA PRIVATE KEY-----
                -----END RSA PRIVATE KEY-----
              run_list:
                - "recipe[starter]"
              initial_attributes:
                charter_cassandra:
                  cassandra:
                    seeds:
                      - __seed_ipaddr__
                      - __host1_ipaddr__
                      - __host2_ipaddr__
            runcmd:
              - [ /usr/bin/chef-client ]

  cassandra_host1:
    type: OS::Nova::Server
    properties:
      name: cassandra-host1
      image: { get_param: ubuntu_image }
      flavor: { get_param: host_size } 
      networks:
        - port: { get_resource: host2_port } 
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __seed_ipaddr__: { get_attr: [seed_port, fixed_ips, 0, ip_address] }
            __host1_ipaddr__: { get_attr: [host1_port, fixed_ips, 0, ip_address] }
            __host2_ipaddr__: { get_attr: [host2_port, fixed_ips, 0, ip_address] }
          template: |
            #cloud-config
            chef:
              install_type: "omnibus"
              omnibus_url: "https://www.chef.io/chef/install.sh"
              force_install: false
              server_url: "https://api.opscode.com/organizations/username"
              log_location: "/var/log/chef-client.log"
              validation_name: "username-validator"
              validation_key: |
                -----BEGIN RSA PRIVATE KEY-----
                -----END RSA PRIVATE KEY-----
              run_list:
                - "recipe[starter]"
              initial_attributes:
                charter_cassandra:
                  cassandra:
                    seeds:
                      - __seed_ipaddr__
                      - __host1_ipaddr__
                      - __host2_ipaddr__
            runcmd:
              - [ /usr/bin/chef-client ]

  cassandra_host2:
    type: OS::Nova::Server
    properties:
      name: cassandra-host2
      image: { get_param: ubuntu_image }
      flavor: { get_param: host_size } 
      networks:
        - port: { get_resource: host1_port } 
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __seed_ipaddr__: { get_attr: [seed_port, fixed_ips, 0, ip_address] }
            __host1_ipaddr__: { get_attr: [host1_port, fixed_ips, 0, ip_address] }
            __host2_ipaddr__: { get_attr: [host2_port, fixed_ips, 0, ip_address] }
          template: |
            #cloud-config
            chef:
              install_type: "omnibus"
              omnibus_url: "https://www.chef.io/chef/install.sh"
              force_install: false
              server_url: "https://api.opscode.com/organizations/username"
              log_location: "/var/log/chef-client.log"
              validation_name: "username-validator"
              validation_key: |
                -----BEGIN RSA PRIVATE KEY-----
                -----END RSA PRIVATE KEY-----
              run_list:
                - "recipe[starter]"
              initial_attributes:
                charter_cassandra:
                  cassandra:
                    seeds:
                      - __seed_ipaddr__
                      - __host1_ipaddr__
                      - __host2_ipaddr__
            runcmd:
              - [ /usr/bin/chef-client ]
outputs:
  seed_public_ip:
    description: Floating IP address of seed server
    value: { get_attr: [ seed_floating_ip, floating_ip_address ] }
