heat_template_version: 2013-05-23

description: Sample Keystone template

resources:
  test_role_a:
    type: OS::Keystone::Role
    properties:
      name: test_role_a

  test_project_a:
    type: OS::Keystone::Project
    properties:
      name: test_project_a
      domain: default
      description: Test project
      enabled: true

  test_group_a:
    type: OS::Keystone::Group
    properties:
      name: test_group_a
      domain: default
      description: Test group
      roles:
        - role: {get_resource: test_role_a}
          domain: default
        - role: {get_resource: test_role_a}
          project: {get_resource: test_project_a}

  test_user_a:
    type: OS::Keystone::User
    properties:
      name: test_user_a
      domain: default
      description: Test user
      enabled: true
      email: abc@xyz.com
      password: password
      default_project: {get_resource: test_project_a}
      groups:
        - {get_resource: test_group_a}
      roles:
        - role: {get_resource: test_role_a}
          domain: default
        - role: {get_resource: test_role_a}
          project: {get_resource: test_project_a}

outputs:
  test_user_a_id:
    value: {get_resource: test_user_a}
  test_group_a_id:
    value: {get_resource: test_group_a}
  test_project_a_id:
    value: {get_resource: test_project_a}
  test_role_a_id:
    value: {get_resource: test_role_a}